import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import SidbarRight from "@/components/shared/SidbarRight";
import SidbarLeft from "@/components/shared/SidbarLeft";
import Footer from "@/components/shared/Footer";
import MainContainer from "@/components/shared/MainContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-gray-800`}>
          <main className="flex flex-row ">
            <SidbarLeft />
            <MainContainer>{children}</MainContainer>
            <SidbarRight />
          </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
