import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import SidbarRight from "@/components/shared/SidbarRight";
import SidbarLeft from "@/components/shared/SidbarLeft";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex flex-row">
            <SidbarRight />
            <div>
              <Navbar />
              {children}
            </div>
            <SidbarLeft />
          </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
