import { ClerkProvider } from "@clerk/nextjs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={` bg-gray-800 w-full h-screen`}>
          <div className="flex mt-20 h-screen justify-center items-center bg-black ">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
